import random

fortunes = [
    "A journey of a thousand miles begins with a single step.",
    "You will soon be selected for a position of importance.",
    "An exciting opportunity will present itself soon.",
    "Happiness is not a destination, it is a way of life.",
    "A faithful friend is a strong defense.",
    "Good things come to those who wait, but better things come to those who hustle.",
    "The best way to predict the future is to create it.",
    "Your hard work will soon pay off.",
    "Don't be afraid to take a chance.",
    "Someone close to you is thinking of you.",
    "Success is in your hands.",
    "You have a magnetic personality.",
    "A new venture will be successful.",
    "Enjoy the good luck that is coming your way.",
    "Patience is a key element of success.",
    "You will conquer your fears.",
    "Expect the best, and the best will happen.",
    "The road to riches is paved with good intentions and hard work.",
    "A pleasant surprise is in store for you.",
    "You will inherit a large sum of money.",
    "Be careful, but don't worry.",
    "A big fortune is coming your way.",
    "Your creativity will lead to unexpected success.",
    "You will make a new, interesting friend.",
    "Opportunities are never lost; someone else takes the ones you miss.",
    "Laughter is the best medicine.",
    "You will live a long, happy life.",
    "Your dreams are closer than you think.",
    "Take time to appreciate small joys.",
    "The greatest risk is not taking one.",
    "You will travel to many exotic places.",
    "Change is coming, embrace it.",
    "You are admired for your honesty.",
    "Believe in yourself and your abilities.",
    "An old flame will re-enter your life.",
    "You will soon achieve a long-held goal.",
    "Your advice is valuable to others.",
    "Look to the stars for guidance.",
    "A joyful reunion is coming soon.",
    "The present moment is filled with joy and wonder.",
    "You will be given a chance to show your skills.",
    "Your wit and charm will open many doors.",
    "All your efforts will soon be rewarded.",
    "Don't worry about the past; the future is bright.",
    "A friend is a present you give yourself.",
    "You have the power to change your life.",
    "Be kind to strangers; you may be entertaining angels unawares.",
    "A hidden talent will soon reveal itself.",
    "Your ability to love will bring you much happiness.",
    "Today is the day to be brave."
]

print(random.choice(fortunes))
